### ISSUE TITLE
Event 事件支持

### ISSUE THREAD

**Issue by Rhain** [NasaTeam/Nasa.js#3]
目前虽然neb.js 提供了订阅事件的接口，但是从官方人员中得知的时候，这个接口并不稳定。
[问题详情](https://github.com/nebulasio/neb.js/issues/53)
官方给的解决方案是自己运行本地节点，这个方案感觉还是有一点繁琐，有没有可能可以提供其他更加方便的解决方案？

**Comment by cssmagic** [comment]
你好，谢谢关注 Nasa.js。

我本人对星云 Event 暂时没有深入了解，短期内在 Nasa.js 上没有相关的开发计划。不过我会继续关注星云在 Event 上的进一步动作，只要时机合适，肯定会加入进来。

如果你有具体的实现相法，欢迎继续讨论，谢谢！

**Comment by cssmagic** [comment]
暂时关闭此 issue。如果需要会重新打开。
